---
name: Add News
on:
  issue_comment:
    types:
      - created
jobs:
  check:
    if: >-
      !github.event.repository.fork && (
        github.event.comment.body == 'please add news'
        || github.event_name == 'pull_request_target'
      )

    runs-on: ubuntu-latest
    steps:
      - name: Create File
        if: contains(steps.check_comment.outputs.comment, 'please add news')
        id: create_file
        uses: actions/checkout@v2
 
      - name: Populate File
        uses: 1arp/create-a-file-action@0.2
        with:
          branch: ${{ github.head_ref }}
          path: "news"
          file: "${{ steps.pr_number }}_news"
          content: |
            ### Enhancements
            * <news item>
            ### Bug fixes
            * <news item>
            ### Deprecations
            * <news item>
            ### Docs
            * <news item>
            ### Other
            * <news item>

      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v2

      - name: Commit File
        if: steps.create_file.outputs
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Add news snippet
          add: "${{ steps.pr_number }}_news"
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run: checkout-repo
