---
name: Add News

on:
  issue_comment:
    types:
      - created      

jobs:
  check:
    if: >-
      !github.event.repository.fork && (
        github.event.comment.body == 'please add news'
        || github.event_name == 'pull_request_target'
      )

    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Add emoji reaction
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'

      - name: Get branch name
        id: extract_branch
        run: |
          # GITHUB_REF contains the branch name on branch triggers
          # GITHUB_HEAD_REF contains the branch name on PR triggers
          GIT_BRANCH=${GITHUB_REF##*/}
          GIT_BRANCH=${GITHUB_HEAD_REF:-$GIT_BRANCH}
          echo "branch=${GIT_BRANCH}" | tee -a $GITHUB_OUTPUT

      - name: News file from template
        run: |
          cp news/TEMPLATE "news/${{ github.event.issue.number }}_${{ steps.extract_branch.outputs.branch }}"

      - name: Checkout the branch we're running on to enable a commit to it
        run: git checkout ${{ github.head_ref }}

      - name: Commit and Add New News File to the Pull Request
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Add news file to this PR"
          add: "news/${{ github.event.issue.number }}_${{ steps.extract_branch.outputs.branch }}"
          branch: ${{ steps.extract_branch.outputs.branch }}
