---
name: Add News

on:
  issue_comment:
    types:
      - created

jobs:
  check:
    if: >-
      !github.event.repository.fork && (
        github.event.comment.body == 'please add news'
        || github.event_name == 'pull_request_target'
      )

    runs-on: ubuntu-latest
    steps:
      - name: Create File
        if: contains(steps.check_comment.outputs.comment, 'please add news')
        id: create_file
        uses: actions/checkout@v2

      - name: Populate File
        uses: 1arp/create-a-file-action@0.2
        with:
#           branch: ${{ github.head_ref }}
          path: "news"
          file: "news.txt"
          content: |
            ### Enhancements
            * <news item>
            ### Bug fixes
            * <news item>
            ### Deprecations
            * <news item>
            ### Docs
            * <news item>
            ### Other
            * <news item>

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Commit File
        if: steps.create_file.outputs
        run: |
          git config --global user.email "${{ github.event.pull_request.user.email }}"
          git config --local user.name "${{ github.event.pull_request.user.login }}"
          git add .
          git commit -m "Add news snippet"
          git push origin ${{ github.head_ref }}
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

