---
name: Add News

on:
  issue_comment:
    types:
      - created      
jobs:
  check:
    if: >-
      !github.event.repository.fork && (
        github.event.comment.body == 'please add news'
        || github.event_name == 'pull_request_target'
      )

    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
 
      - name: Add emoji reaction
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: News file from template
        run: |
          cp news/TEMPLATE "news/${{ github.event.issue.number }}_${{ steps.extract_branch.outputs.branch }}"

      - name: Check status of the (presumed) PR branch
        run: |
          git status
          git checkout -b $RANDOM

      - name: Commit and Add New News File to the Pull Request
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Add news file to this PR"
          add: "news/${{ github.event.issue.number }}_${{ steps.extract_branch.outputs.branch }}"
          # branch: ${{ steps.extract_branch.outputs.branch }}
